In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('50_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
X= data.iloc[:,:-1]

X = pd.get_dummies(X)
X.shape
# X

(50, 6)

In [4]:
y= data.iloc[:,-1].values
y.shape

(50,)

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
labelencoder_X = LabelEncoder()
X.iloc[:, 3]= labelencoder_X.fit_transform(X.iloc[:, 3])
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
X

array([[1.0000000e+00, 0.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05, 0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05, 1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.4437241e+05, 1.1867185e+05,
        3.8319962e+05, 0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05, 1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.3187690e+05, 9.9814710e+04,
        3.6286136e+05, 0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 1.3461546e+05, 1.4719887e+05,
        1.2771682e+05, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.3029813e+05, 1.4553006e+05,
        3.2387668e+05, 1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, train_size=0.7,random_state=0)
X_train.shape

(35, 7)

In [8]:
X_test.shape

(15, 7)

In [9]:
y_test.shape

(15,)

In [10]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm1 = lm.fit(X_train, y_train)
pred = lm1.predict(X_test)
pred

array([104282.76472172, 132536.88499212, 133910.85007767,  72584.77489418,
       179920.9276189 , 114549.31079233,  66444.43261347,  98404.96840123,
       114499.82808602, 169367.50639895,  96522.62539981,  88040.67182871,
       110949.99405526,  90419.1897851 , 128020.46250064])

In [11]:
from sklearn.metrics import confusion_matrix
# confusion_matrix(y_test, pred)

In [12]:
X 

array([[1.0000000e+00, 0.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05, 0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05, 1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.4437241e+05, 1.1867185e+05,
        3.8319962e+05, 0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05, 1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.3187690e+05, 9.9814710e+04,
        3.6286136e+05, 0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 1.3461546e+05, 1.4719887e+05,
        1.2771682e+05, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.3029813e+05, 1.4553006e+05,
        3.2387668e+05, 1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0

In [13]:
import statsmodels.regression.linear_model as sm
# add a column of ones as integer data type
X = np.append(arr = np.ones((50, 1)).astype(int), 
              values = X, axis = 1)
# choose a Significance level usually 0.05, if p>0.05
#  for the highest values parameter, remove that value
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
ols = sm.OLS(endog = y, exog = X_opt).fit()
ols.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Wed, 23 Jun 2021   Prob (F-statistic):           8.51e-29
Time:                        08:50:04   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.342e+04   4429.985      7.543      0.000    2.45e+04    4.23e+04
x1          1.674e+04   2632.492      6.360      0.000    1.14e+04     2.2e+04
x2          1.667e+04   2623.602      6.355      0.000    1.14e+04     2.2e+04
x3             0.8057      0.046     17.646      0.000       0.714       0.898
x4            -0.0268      0.052     -0.520      0.606      -0.131       0.077
x5             0.0272      0.017      1.627      0.111      -0.006       0.061
==============================================================================
Omnibus:                       14.785   Durbin-Watson:                   1.281
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.242
Skew:                          -0.949   Prob(JB):                     2.44e-05
Kurtosis:                       5.568   Cond. No.                     1.02e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.7e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [14]:
# remove the 4th column as it has the highest value
x_opt = X[:, [0, 1, 2, 3, 5]]
ols = sm.OLS(endog = y, exog = x_opt).fit()
ols.summary()

# remove the 5th column as it has the highest value
x_opt = X[:, [0, 1, 2, 3]]
ols = sm.OLS(endog = y, exog = x_opt).fit()
ols.summary()

# remove the 3rd column as it has the highest value
x_opt = X[:, [0, 1, 2]]
ols = sm.OLS(endog = y, exog = x_opt).fit()
ols.summary()

# remove the 2nd column as it has the highest value
x_opt = X[:, [0, 1]]
ols = sm.OLS(endog = y, exog = x_opt).fit()
ols.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.021
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     1.043
Date:                Wed, 23 Jun 2021   Prob (F-statistic):              0.312
Time:                        08:50:04   Log-Likelihood:                -600.12
No. Observations:                  50   AIC:                             1204.
Df Residuals:                      48   BIC:                             1208.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.039e+05   9771.391     10.634      0.000    8.43e+04    1.24e+05
x1          1.228e+04    1.2e+04      1.021      0.312   -1.19e+04    3.65e+04
==============================================================================
Omnibus:                        0.079   Durbin-Watson:                   0.073
Prob(Omnibus):                  0.961   Jarque-Bera (JB):                0.190
Skew:                           0.087   Prob(JB):                        0.909
Kurtosis:                       2.753   Cond. No.                         3.19
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

## automating the backward elimination

In [15]:
import statsmodels.api as sm
X = np.append(arr = np.ones((50, 1)).astype(int), values = X, axis = 1)
def backwardElimination(X, sl):
    length = x_opt.shape[1]
    for i in range(length):
        regressor_OLS = sm.OLS(y, x_opt).fit()
        maxp = max(regressor_OLS.pvalues).astype(float)
        if maxp > sl:
            for j in range(length):
                if (regressor_OLS.pvalues[j].astype(float) == maxp):
                    X_opt = np.delete(x_opt, j, 1)
                    
    return regressor_OLS.summary()
SL = 0.05
X_opt = np.array(X[:, [0, 1, 2, 3, 4, 5]], dtype= float)
Best_feature, OLS_summary = backwardElimination(x_opt, SL)
X_Modeled

TypeError: cannot unpack non-iterable Summary object