In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# names = ['id','SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']
data = pd.read_csv('iris.csv')
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
x = data.values[:, 1:-1]
x.shape

(150, 4)

In [4]:
y = data['Species']
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [5]:
lencoder = LabelEncoder()
mod = lencoder.fit_transform(y)
y = mod 
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [1]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)


NameError: name 'train_test_split' is not defined

In [7]:
x_train.shape

(105, 4)

In [8]:
y_train.shape

(105,)

In [9]:
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(x_train, y_train)


KNeighborsClassifier()

In [10]:
y_pred=neigh.predict(x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [11]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
confusion_matrix( y_test, y_pred)

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)

In [12]:
len(y_pred)

45

In [13]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [14]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9777777777777777

# support Vector Machines (SVM)

In [15]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
scx = StandardScaler()
scaled = scx.fit_transform(x)
scaled

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [16]:
classifier = SVC(kernel='linear', random_state = 0)
classifier.fit(x_train, y_train)
mpred = classifier.predict(x_test)
confusion_matrix( y_test, mpred)
accuracy_score(y_test, mpred)

0.9777777777777777

In [17]:
classifier.score(x_train, y_train)

0.9809523809523809

In [18]:
classifier.score(x_test, y_test)

0.9777777777777777

In [19]:
classi = SVC(kernel='poly', random_state = 0)
classi.fit(x_train, y_train)
ppred = classi.predict(x_test)
confusion_matrix( y_test, ppred)
accuracy_score(y_test, ppred)

0.9777777777777777

In [20]:
classi = SVC(kernel='rbf', random_state = 0)
classi.fit(x_train, y_train)
rpred = classi.predict(x_test)
confusion_matrix( y_test, rpred)
accuracy_score(y_test, rpred)

0.9777777777777777

In [21]:
classi = SVC(kernel='sigmoid', random_state = 0)
classi.fit(x_train, y_train)
rpred = classi.predict(x_test)
confusion_matrix( y_test, rpred)
accuracy_score(y_test, rpred)

0.24444444444444444

In [22]:
svc = SVC(kernel='precomputed', random_state = 0)
kernel_train = np.dot(x_train, x_train.T)  # linear kernel

svc.fit(kernel_train, y_train)

#kernel_test = np.dot(X_test, X_train[svc.support_, :].T)
kernel_test = np.dot(x_test, x_train.T)
y_pred = svc.predict(kernel_test)
confusion_matrix( y_test,y_pred)
accuracy_score(y_test, y_pred)

0.9777777777777777

In [29]:
from sklearn.naive_bayes import GaussianNB
gsn = GaussianNB()
gsn.fit(x_train, y_train)

GaussianNB()

In [30]:
y_pred = gsn.predict(x_test)

In [31]:
confusion_matrix( y_test, y_pred)
# accuracy_score(y_test, y_pred)

array([[16,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 11]], dtype=int64)

In [32]:
classifier.score(x_test, y_test)

0.9777777777777777